joomla-extensions/patchtester

administrator/components/com_patchtester/PatchTester/View/Pulls/PullsHtmlView.php
This PR re-apply the toolbar icon fix that was added here: https://github.com/joomla-extensions/patchtester/pull/23
=> Re-apply the toolbar icon fix

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
as reported #47 you are unable to apply a patch on postgresql
the issue arise cause we are using LIKE on a bigint field ```pull_id```
```
WHERE ("a"."title" LIKE '%6263%') OR ("a"."pull_id" LIKE '%6263%')
```
we need to use ``` = ``` instead
=> PostgreSQL - error apply/revert a patch

administrator/components/com_patchtester/PatchTester/View/Fetch/tmpl/default.php
@mbabker fetcher.js is crying that Joomla is not defined. This is due to the fact that behavior.framework was loading as well core.js, but not anymore. Therefore we should load it ourselves. Sorry I didn’t catch that before 😕
=> core.js is needed

.travis.yml
enable Travis on PHP 7 and use the new infrastructure, PHP CS only on PHP 5.3
see that the unit test still works. ;)
=> Travis on PHP 7 and the new infrastructure

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
Need to move the `is_numeric($search)` check to it's own condition since we are not striping off the first 3 characters when searching by a pure numeric case
Also better to search with a "like" rather than a direct equals so we can match partial number sequences.
This resolves an unnoticed inconsistency with #118
=> Move the is_numeric($search) to it's own condition

administrator/components/com_patchtester/install/sql/mysql/install.sql, administrator/components/com_patchtester/script.php
Create patchtester tables with InnoDB and utf8mb4_unicode_ci.
1. Install patchtester beta 4 with this patch integrated on a joomla latest staging (clean install). 
[com_patchtester-beta-4-ut8mb4.zip](https://github.com/joomla-extensions/patchtester/files/154814/com_patchtester-beta-4-ut8mb4.zip)
2. Check if everything is working fine.
To not cause issues added a drop to existing tables first.
Not an expert in databases, so please check if anything more is needed.
=> Use InnoDB and utf8mb4_unicode_ci in the patchtester too

administrator/components/com_patchtester/PatchTester/Controller/ResetController.php
the reset message type should be `notice`, not `info`
=> notice, not info

administrator/components/com_patchtester/script.php
This removes the frontend file `components/com_patchtester/patchtester.php` it contains nothing and is not longer included into the package: https://github.com/joomla-extensions/patchtester/blob/master/build/patchtester/build.sh
This can't be tested.
=> Remove the frontend file

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
Pull Request for Issue #175 .
In standard SQL bigint field "pull_id" doesn't like `LIKE` operator
install com_patchtester, and check that the search work as expected
=> Postgresql - bigint field "pull_id" doesn't like LIKE operator - #175

administrator/components/com_patchtester/PatchTester/Model/PullModel.php
Pull Request for Issue https://github.com/joomla-extensions/patchtester/issues/177.
Auto changes media version when appluing/reverting a patch.
1. Check the media version in page source
2. Apply one patch
3. Check the media version in page source changed
3. Revert the patch
4. Check the media version in page source changed again
=> Change media version when applying/reverting a patch

manifest.xml
Add 3.0.0 beta to the update server with beta update tag
Merge this set the update stability in the backend to beta you see the update.
Switch back to stable (default) no update should be shown.
=> Add 3.0.0 beta to the update server with beta update tag

manifest.xml
with the merge of https://github.com/joomla/joomla-cms/pull/17619. in the 3.9 branch
added the `<sha384></sha384>`  tag to the manifest file
on joomla < 3.9 nothing change
on joomla 3.9 the checksum is checked
=> add sha384 signature to manifest.xml

administrator/templates/atum/html/com_patchtester/pulls/default.php
The ```Table Options``` button in the patchtester component is changed to ```Filter Options```( like for any other Joomla component)
None
=> [4.0] Change 'Table Options' to 'Filter Options'

administrator/components/com_patchtester/install/sql/updates/mysql/2.0.0.sql, administrator/components/com_patchtester/install/sql/updates/postgresql/2.0.0.sql, administrator/components/com_patchtester/install/sql/updates/sqlsrv/2.0.0.sql
Pull Request for Issue [#108 (comment)](https://github.com/joomla-extensions/patchtester/issues/186#issuecomment-473627667).
Correct 2.0.0 schema updates so that they fit to 2.0.0 new installation and so the 3.0.0 schema updates won't fail.
Try to install patch tester 3.0.0 beta 4 on Joomla 3.9.6.
Result: See Issue [#108 (comment)](https://github.com/joomla-extensions/patchtester/issues/186#issuecomment-473627667).
Do the same with a patched package modified by the changes in this PR.
You can create such package by downloading the zip, unpacking it, changing the files by those downloaded from this PR, packing back into a new zip in the same way and install that zip with upload file.
Result: Installation successful.
=> Correct 2.0.0 schema updates

administrator/components/com_patchtester/PatchTester/Model/PullModel.php
Pull Request for Issue #240 .
Use DIRECTORY_SEPARATOR for expode and implode of the path to files to be backed up so that later creating the directories for the backups doesn't fail.
I don't know if this is the right way to fix it, but it works here.
See issue #240 .
=> [4.0] Fix applying patches failing on Linux hosts

administrator/components/com_patchtester/PatchTester/Controller/ResetController.php
Fixes following PHP notice:
> PHP Notice:  Undefined variable: revertErrored in /joomla-cms-4.0-dev/administrator/components/com_patchtester/PatchTester/Controller/ResetController.php on line 84
>
Code review: The mistake is obvious. Variable `$revertErrored` is checked even if not set before. Moved initialization of this variable out from the 2 if clauses up to the top.
=> Fix PHP notice in ResetController

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
Corrects `implode()` argument order to fix notices in PHP 7.4.
Code review.
=> Correct implode() argument order

administrator/components/com_patchtester/install/sql/updates/postgresql/4.0.0.sql
Fixes SQL error on PostgreSQL.
Update from 3.0 to 4.0.
`#__patchtester_chain` doesn't exist.
Fixing with Database fixer doesn't work.
With patch it works.
=> [4.0] Error in PostgreSQL update SQL

administrator/components/com_patchtester/PatchTester/Model/PullModel.php
Pull Request for Issue #257 .
Delete file `libraries/autoload_psr4.php` when applying or reverting patches on Joomla 4 and later.
Patched Patchtester package for testing this PR can be downloaded from [https://test5.richard-fath.de/com_patchtester_4.0.0.beta3-dev-5.zip](https://test5.richard-fath.de/com_patchtester_4.0.0.beta3-dev-5.zip).
Check that applying and reverting CMS patches on Joomla 4 which move around class files or rename classes works, and after having applied such a patch neither backend nor frontend are broken in a way which could be fixed by deleting file `libraries/autoload_psr4.php`.
Currently available examples of such PR's:
[https://github.com/joomla/joomla-cms/pull/27643](https://github.com/joomla/joomla-cms/pull/27643) …
=> Delete autoload_psr4.php when applying or reverting patches on Joomla 4 and later.

administrator/components/com_patchtester/PatchTester/Model/PullModel.php
With PR #258 deletion of autoload_psr4.php was added to the Patchtester for J4.
With PR [https://github.com/joomla/joomla-cms/pull/28436](https://github.com/joomla/joomla-cms/pull/28436) the location of that file has changed in the CMS.
This PR here adapts the Patchtester to that change.
Code review.
Or use following patched patchtester package and check that applying and reverting patches with or without CI server option still works as well or bad as before: [https://test5.richard-fath.de/com_patchtester_4.0.0.beta3-dev-7.zip](https://test5.richard-fath.de/com_patchtester_4.0.0.beta3-dev-7.zip).
=> Update path to autoloader file to changes in J4

administrator/components/com_patchtester/PatchTester/Model/PullModel.php
Use the namespace mapper class to regenerate the extension namespace map instead of just deleting it. Avoid the use of hardcoded file path.
Check that extension namespace map is still regenerated after applying/reverting patches.
=> [4.0] Use namespace mapper to regenerate namespace map

administrator/components/com_patchtester/PatchTester/Helper.php
Pass the token via the header and not via query parameter.
Install the latest patchtester
setup token access
do some requests to github
github sends you this
apply the patch
this should not happen any more
A change to the upstream project has been redjected so we have to fix that locally for now i guess.
=> Avoid github deprecation mails when using the token

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
Since commit https://github.com/joomla-extensions/patchtester/commit/4592caba1e4d6a86701828002f93d9a905d4cb3f , the filter for applied or not applied is broken.
This PR here fixes it.
Install Patchtester 4 with the current development status (master branch). You can find a package here: [https://test5.richard-fath.de/com_patchtester_4.0.0.rc4-dev.zip](https://test5.richard-fath.de/com_patchtester_4.0.0.rc4-dev.zip).
Then fill in your GitHub access token in the options and fetch the pull requests.
Then use the filter for applied or not applied patches.
It fails with SQL error about not existing database column "pulls.applied". 
It works.
=> Fix SQL error missing column "pulls.applied" breaking the "Applied" filter

administrator/components/com_patchtester/config.xml
Prevents double display of the description of the password field
=> Duplicate description

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default_items.php
Pull Request for Issue #311 .
Adapt to J4's change to BS5 for the badges: Use classes `bg-...` as suggested by @ceford , thanks for reporting and suggesting.
Other glitches from the BS5 change I haven't seen yet.
Install Patchtester 4 on a current 4.0-dev branch or latest 4.0 nightly build or the last beta, which all have already the change to BS5 included.
Fetch the pull requests and apply one patch to see the different colours.
Result:
Apply the changes from this PR and refresh the page,
Result:
=> Adapt CSS classes for badges to BS5

administrator/components/com_patchtester/PatchTester/GitHub/GitHub.php, administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
Pull Request for Issue #314 .
Use pulls rest API endpoint instead of issues endpoint to fetch the list of PRs. Using issues endpoint caused only a subset of PRs to be retrieved.
Applying change make last 100 PR (batchsize) to be listed in the patch tester admin.
=> 314 missing pulls

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
I use patch tester for testing PR on Joomla 4 and found that it could not fetch all the PRs (only 5 pages, mean 100 PRs). I tried to debug code and it seems Link needs to be changed to link (l in lower case). I made that change and were able to fetch all PRs.
1. Try to fetch PRs
2. Before patch: Only latest 100 PRs are fetched. After patch, all PRs are fetched.
=> Fix Fetch PRs

administrator/components/com_patchtester/PatchTester/View/Pulls/PullsHtmlView.php
no more need for a warning if j4 as it is stable now
=> no more need for a warning if j4

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php
Pull Request for Issue #335 .
- changing id of tooltip element from `filter[search]-desc` to `filter-search-desc`
- doing so makes it the same implementation as done by Joomla com_content article overview
=> adjust tooltip id by

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default_items.php
#340 
By default badges do not have hover styling 
```
Examples 
Badges scale to match the size of the immediate parent element by using relative font sizing and em units. As of v5, badges no longer have focus or hover styles for links.
```
so in order to do so we have the choice of creating a new .css file and adding our own stylings or use the inbuilt bs5 button behavior.  I chose the latter.
The effect is subtle but this is due to how atum handles things.  This issue would be best for @JAT
install patch tester.
apply patch
notice the subtle shift in background color & flicker on hover
=> fixes hover issues

.github/workflows/crowdin-wf.yml
Translations are not up to date; Github Action for crowdin is not running
Update crowdin action; for reference see [commit](https://github.com/joomla/joomla.org/commit/1735af1f6903d361b2b3e0a60d8d0c090116b53d) in https://github.com/joomla/joomla.org
@roland-d
=> update crowdin action

administrator/components/com_patchtester/patchtester.xml, build/patchtester/release.php
see https://github.com/joomla/joomla-cms/pull/27162 for creation date
alternative only `'Y-m'`
remove version attribute (no longer used since 4.0)
=> update creation date format

administrator/components/com_patchtester/src/Controller/StartfetchController.php, administrator/components/com_patchtester/tmpl/fetch/default.php, administrator/components/com_patchtester/tmpl/pulls/default.php, media/com_patchtester/joomla.asset.json, media/com_patchtester/js/fetcher.js
=> Drop jQuery, fix a number of XSS

media/com_patchtester/joomla.asset.json, media/com_patchtester/js/patchtester.js
@roland-d this is a small clean up, please test it before merging 😀
=> Update js scripts

administrator/components/com_patchtester/src/Controller/StartfetchController.php, administrator/components/com_patchtester/src/GitHub/GitHub.php, administrator/components/com_patchtester/src/Model/PullModel.php, administrator/components/com_patchtester/src/Model/PullsModel.php, manifest.xml
Fix GitHub API response handling
Updated the `<sha384>` hash in `manifest.xml` to reflect the latest release package checksum.
=> Fix GitHub API response handling for Joomla Framework 4
