joomla-extensions/patchtester

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php

Rather than having 1 query per PR - this moves all the PR's into one database query which hopefully should have a major performance impact.
Untested as currently don't have the dataspeed on my mobile to actually download all the PR's :P will try in the office tomorrow morning

Improve performance by only making 1 query

---

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php

This PR add the chosen css that makes the dropdown looking better (as we have in core)

Adding chosen css for dropdowns

---

administrator/components/com_patchtester/install/sql/sqlsrv/install.sql

MSSQL doesn't seem to like that!

Remove if not existst on _patchtester_pulls

---

administrator/components/com_patchtester/install/sql/sqlsrv/install.sql

The limit of 5000 seems to be to much for SQL2012

description nvarchar limit to 4000

---

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php
administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default_items.php

Mootools is not needed here, so lets drop it!
Also the inline script is better to go through API

Remove mootools

---

administrator/templates/hathor/html/com_patchtester/pulls/default.php
administrator/templates/hathor/html/com_patchtester/pulls/default_items.php

@mbabker ~~This also needs some update in hathor layouts/joomla/toolbar/popup.php~~
~~I’ll post the code here to remember to create a PR in joomla~~
```php
echo JHtmlBootstrap::renderModal(
'modal-'. $name, array(
'url' => $doTask,
'title' => $text,
'width' => '800px',
'height' => '300px',
'footer' => '<button class="btn" data-dismiss="modal" aria-hidden="true">'
. JText::_("JLIB_HTML_BEHAVIOR_CLOSE") . '</button>'
)
);
?>
<a class="modal toolbar" data-toggle="modal" href="#modal-<?php echo $name; ?>">
<span class="<?php echo $class; ?>"></span>
<?php echo $text; ?>
</a>
```

Hathor is broken

---

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php

To test 
Before PR
Enter any value in the filter column and you get an error
After PR
Make sure that text and numeric filters work

Fix search

---

README.md

Readme.md with ordered list

---

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php

To test search for "id:xxxxx" where xxxxx is the pull request id.

Resolve issue when searching by pull id "id:xxxxx"

---

administrator/components/com_patchtester/patchtester.xml

use tabs instead of spaces in the patchtester.xml
nothing to test here :smile:

Use tabs in the patchtester.xml

---

administrator/components/com_patchtester/PatchTester/Model/PullModel.php

Pull Request for Issue #132 .
Added non production files to the exclude array
- Install a patch that changes the build.xml
- you are unable to install the patch
- add this changes
- you are able to install the patch

Added non production files to the exclude array

---

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php

simple change to fix tfoot colspan

fix tfoot colspan

---

README.md

-After the session at JDFR, some reported they haven't seen it was available in fr-FR
-This will perhaps encourage others to do the same in other languages

Link to localized versions of the README

---

administrator/components/com_patchtester/config.xml

just code style + autocomplete = off
Code review

code style + autocomplete = off

---

administrator/components/com_patchtester/config.xml

Pull Request for Issue https://github.com/joomla-extensions/patchtester/issues/158
Solves https://github.com/joomla-extensions/patchtester/issues/158
See https://github.com/joomla-extensions/patchtester/issues/158

empty user, pass and token on change

---

administrator/components/com_patchtester/PatchTester/Controller/AbstractController.php
administrator/components/com_patchtester/script.php

Pull Request for Issue #173
Changes typehint.  Pending acceptance of https://github.com/joomla/joomla-cms/pull/12650 otherwise version conditionals and a non-typehinted constructor argument are required.
Also bumps minimum to 3.7.
Component works.

Controller typehint

---

administrator/components/com_patchtester/PatchTester/GitHub/GitHub.php

allow login github credential with '#'

---

administrator/components/com_patchtester/install/sql/postgresql/install.sql
administrator/components/com_patchtester/patchtester.xml

To work with J4
Pull Request for Issue #219 .
Add pgsql driver.
Select the postgreSQL (PDO) driver and install this component.

Add PostgreSQL (PDO) driver.

---

.drone.yml
administrator/components/com_patchtester/PatchTester/Controller/DisplayController.php
administrator/components/com_patchtester/PatchTester/Model/PullModel.php
administrator/components/com_patchtester/PatchTester/Model/PullsModel.php
administrator/templates/atum/html/com_patchtester/pulls/default.php
administrator/templates/atum/html/com_patchtester/pulls/default_items.php
composer.json
composer.lock

This adds Drone as CI and updates to latest codestyle. Due to permissions reasons, drone is not active yet.

Updating to use Drone and newest codestyle

---

administrator/components/com_patchtester/PatchTester/View/Pulls/PullsHtmlView.php
administrator/components/com_patchtester/language/en-GB/en-GB.com_patchtester.ini

Removing warning message for Joomla 4

---

README.md

Current patch tester walk-through tutorial as documented in https://docs.joomla.org/Testing_Joomla!_patches
replaced 2013 video with 2017 version
verify video plays and is relevant

Update patch tester video tutorial

---

administrator/components/com_patchtester/PatchTester/Model/PullModel.php

Pull Request for Issue #233 .
Redo of PR #249 for master branch.
See the title.
Verify that applying and reverting a PR which requires the CI server still works without issues.
I've tested with PR [https://github.com/joomla/joomla-cms/pull/28405](https://github.com/joomla/joomla-cms/pull/28405).
After apply, check that all changes have been applied and the css or js to be compiled with these changes have been compiled.
After revert, check that all changes have been reverted, also those in the css or js to be compiled.

Use HttpFactory to fetch zip file from CI server

---

administrator/components/com_patchtester/install/sql/mysql/install.sql

Pull Request for Issue #234 .
See title.
Code review.

Clean up one more SQL file - most important one - from patchtester chain

---

administrator/components/com_patchtester/PatchTester/View/Pulls/PullsHtmlView.php

changes icon names to be fa compliant
see https://github.com/joomla/joomla-cms/pull/28075

makes icons conform to pr #28075 in J! 4.0-dev

---

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php

Fix the PHPCS errors reported by Drone since the following commit: https://github.com/joomla-extensions/patchtester/commit/4592caba1e4d6a86701828002f93d9a905d4cb3f
Check that Drone PHPCS passes.

Fix PHPCS errors from previous commit "Add a label filter"

---

administrator/components/com_patchtester/PatchTester/View/Pulls/tmpl/default.php

Simple PR to replace a hard coded string with the correct translatable global language key

Untranslated string

---

administrator/components/com_patchtester/PatchTester/GitHub/GitHub.php
administrator/components/com_patchtester/PatchTester/Model/PullsModel.php

Pull Request for Issue # 314.
Use pulls rest API endpoint instead of issues endpoint to fetch the list of PRs. Using issues endpoint caused only a subset of PRs to be retrieved.
Applying change make last 100 PR (batchsize) to be listed in the patch tester admin.

314 missing pulls j4

---

administrator/components/com_patchtester/PatchTester/Model/PullsModel.php

fix php codestyle errors reported by drone
drone report no php codestyle errors

fix php cs

---

.github/workflows/crowdin-wf.yml

checkout@v3 (node16)
@roland-d

update crowdin action

---

administrator/components/com_patchtester/src/Model/PullsModel.php

fix pulls filters
use bind for database query
test if filters work (applied, rtc, npm, draft)

fix pulls filter
